global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'trendscope-monitor'

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ML Service metrics
  - job_name: 'ml-service'
    static_configs:
      - targets: ['ml-service:8000']
    metrics_path: '/metrics'

  # Kafka Exporter (optional - requires kafka-exporter service)
  # - job_name: 'kafka'
  #   static_configs:
  #     - targets: ['kafka-exporter:9308']

  # Node Exporter (optional - for system metrics)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
